[versions]
spring-boot = "3.3.2"
spring-dependency-management = "1.1.4"
junit = "5.10.2"
junit-platform = "1.10.2"
springdoc = "2.5.0"
lombok = "1.18.32"
jjwt = "0.11.5"
jackson = "2.17.1"
testcontainers = "1.20.1"
tika = "2.9.2"
archunit = "1.2.1"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-data-ldap = { module = "org.springframework.boot:spring-boot-starter-data-ldap", version.ref = "spring-boot" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client", version.ref = "spring-boot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "spring-boot" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "spring-boot" }
spring-boot-starter-quartz = { module = "org.springframework.boot:spring-boot-starter-quartz", version.ref = "spring-boot" }
spring-boot-starter-batch = { module = "org.springframework.boot:spring-boot-starter-batch", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }
h2-database = { module = "com.h2database:h2" }
spring-context = { module = "org.springframework:spring-context" }
spring-retry = { module = "org.springframework.retry:spring-retry", version = "2.0.7" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.1.8" }
springdoc-openapi-starter = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
ulid-creator = { module = "com.github.f4b6a3:ulid-creator", version = "5.2.0" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "spring-boot" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
tika-core = { module = "org.apache.tika:tika-core", version.ref = "tika" }
spring-batch-test = { module = "org.springframework.batch:spring-batch-test" }
archunit-junit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka", version.ref = "spring-boot" }
embedded-redis = { module = "it.ozimov:embedded-redis", version = "0.7.3" }

[bundles]
spring-boot-core = ["spring-boot-starter", "spring-boot-starter-validation"]
spring-boot-security = ["spring-boot-starter-security", "spring-boot-starter-oauth2-client", "spring-boot-starter-data-ldap"]
spring-test = ["spring-boot-starter-test", "spring-security-test"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
