management:
  tracing:
    enabled: true
    sampling:
      probability: 0.1
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
      compression: gzip
      headers:
        Authorization: ${OTEL_EXPORTER_OTLP_HEADERS:}
logging:
  pattern:
    level: "%5p trace_id=%X{traceId:-} span_id=%X{spanId:-}"

draft:
  notification:
    publisher: ${DRAFT_NOTIFICATION_PUBLISHER:event} # event | log | kafka

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    client-id: ${KAFKA_CLIENT_ID:clear-reg-server}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
